const FALLBACK_BRIEFING={updatedAt:new Date().toISOString(),sections:[
{id:'az',title:'🇦🇿 Азербайджан',items:[]},{id:'ru',title:'🇷🇺 Россия',items:[]},{id:'world',title:'🌍 Мир',items:[]},{id:'economy',title:'💰 Экономика',items:[]},{id:'incidents',title:'🚨 Происшествия',items:[]},{id:'science',title:'🔬 Наука',items:[]},{id:'weather',title:'🌦 Погода',items:[]},{id:'ai',title:'🤖 AI',items:[]},{id:'tech',title:'📱 Технологии',items:[]},{id:'sport',title:'⚽ Спорт',items:[]}
]};
let briefing=FALLBACK_BRIEFING;
function getGreeting(){const h=new Date().getHours();if(h>=5&&h<12)return'Доброе утро';if(h>=12&&h<18)return'Добрый день';if(h>=18)return'Добрый вечер';return'Доброй ночи'}
function formatDate(d=new Date()){return new Intl.DateTimeFormat('ru-RU',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(d)}
function formatTime(iso){const d=iso?new Date(iso):new Date();return new Intl.DateTimeFormat('ru-RU',{hour:'2-digit',minute:'2-digit',day:'2-digit',month:'2-digit'}).format(d)}
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function itemCard(i,tag){const title=escapeHtml(i.title||'Новость');const text=escapeHtml(i.text||i.what||'Подробности уточняются.');const source=escapeHtml(i.source||'');const url=i.url?String(i.url):'';return `<article class="news">${tag?`<div class="tag">${tag}</div>`:''}<div class="newsTitle">${title}</div><div class="newsText">${text}</div>${source?`<div class="newsMeta">Источник: ${source}</div>`:''}${url?`<a class="readMore" href="${escapeHtml(url)}" target="_blank" rel="noopener">Читать полностью →</a>`:''}</article>`}
function render(){document.getElementById('greeting').textContent=getGreeting();document.getElementById('dateLine').textContent='📅 '+formatDate();document.getElementById('updatedLine').textContent='Последнее обновление: '+formatTime(briefing.updatedAt);const all=briefing.sections.flatMap(s=>(s.items||[]).map(x=>({...x,section:s.title})));document.getElementById('topStories').innerHTML=all.slice(0,8).map((x,i)=>itemCard(x,i===0?'🟥 Самое важное':i<3?'🟨 Важно':'🟦 Стоит знать')).join('')||'<div class="empty">Новости загружаются.</div>';document.getElementById('quick').innerHTML=briefing.sections.map(s=>`<a href="#${s.id}">${s.title}</a>`).join('');document.getElementById('sections').innerHTML=briefing.sections.map(s=>`<section class="card" id="${s.id}"><h2>${s.title}</h2>${(s.items||[]).map(x=>itemCard(x)).join('')||'<div class="empty">Пока нет свежих новостей в этом разделе.</div>'}</section>`).join('')}
async function loadBriefing(){try{const r=await fetch('briefing.json?ts='+Date.now(),{cache:'no-store'});if(r.ok){briefing=await r.json()}}catch(e){console.warn('briefing.json не загрузился, используется резервная структура',e)}render()}
async function testNotify(){if(!('Notification' in window)){alert('Уведомления не поддерживаются этим браузером.');return}const p=await Notification.requestPermission();if(p==='granted')new Notification('My Brief',{body:'Тестовое уведомление включено.'})}
if('serviceWorker' in navigator){navigator.serviceWorker.register('service-worker.js')}loadBriefing();
